In [1]:
import os
import pandas as pd
import numpy as np
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from scipy.io import loadmat, savemat
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
import random
from sklearn.neighbors import KNeighborsClassifier

In [2]:
p_num=55
a = []

for i in range(10):
    a.append(np.ceil((np.random.permutation(p_num)+1)/(p_num/5.0)).reshape(1,p_num))

a = np.array(a)
len(a)

10

In [3]:
normal_Y=np.array([35,45,55,65,83,104,106,108,110,112,126,137,151,154,163,26,53,105]);
normal_O=np.array([1,12,14,20,41,62,77,133,153,15,42,44,64,89,160,161]);
 
mtom_Y=np.array([25,47,50,56,59,63,92,111,51,58,94,102,114,144,122,38,68,91,95,98,138]);
mtom_O=np.array([2,4,96,118,125,142,21,67,101,115,127,136,99,116,130,11,49,82]);
 
severe_Y=np.array([24,28,31,34,36,40,60,76,128,135,57,66,71,79,109,139,152]);
severe_O=np.array([30,43,46,69,70,73,75,86,97,117,129,131,134,156,162,19,23,74,78,84,85]);

normal=np.array([35,45,55,65,83,104,106,108,110,112,126,137,151,154,163,26,53,105,
                 1,12,14,20,41,62,77,133,153,15,42,44,64,89,160,161]);
mtom=np.array([25,47,50,56,59,63,92,111,51,58,94,102,114,144,122,38,68,91,95,98,138,
               2,4,96,118,125,142,21,67,101,115,127,136,99,116,130,11,49,82]);
severe=np.array([24,28,31,34,36,40,60,76,128,135,57,66,71,79,109,139,152,
                 30,43,46,69,70,73,75,86,97,117,129,131,134,156,162,19,23,74,78,84,85]);

control_num=np.array([1,12,14,20,41,62,77,133,153,15,42,44,64,89,160,161,
                     2,4,96,118,125,142,21,67,101,115,127,136,99,116,130,11,49,82,
                     30,43,46,69,70,73,75,86,97,117,129,131,134,156,162,19,23,74,78,84,85]);


Young=np.array([35,45,55,65,83,104,106,108,110,112,126,137,151,154,163,26,53,105,
               25,47,50,56,59,63,92,111,51,58,94,102,114,144,122,38,68,91,95,98,138,
               24,28,31,34,36,40,60,76,128,135,57,66,71,79,109,139,152]);

len(control_num)

55

In [4]:
num = 0
accuracy2 =[]
feature_num=101 #97
result2 = np.zeros((2,2)) #

for k in range(len(a)):
    b = a[k]
    
    for m in range(1,6):
        index_test = np.where(b == m)
        index_train = np.where(b != m)
        
        test_set = np.empty((0,feature_num))
        train_set = np.empty((0,feature_num))
        test_set_label = np.empty((0,1))
        train_set_label = np.empty((0,1))
        train_set2 = np.empty((0,feature_num))
        test_set_label2 = np.empty((0,1))
        
        test = index_test[1]
        train = index_train[1]
        
        print("{}번째 아우터 루프의 {}번째 테스트 인덱스".format(k, m))
        print(test)
        print("{}번째 아우터 루프의 {}번째 트레인 인덱스 ".format(k, m))
        print(train)
        print("\n")
        
        for n in test:
                        
            test_label = np.empty((0,1))
            if np.isin(normal,control_num[n]).sum() == 1:
                test_label = np.array([[1]])
                test_data = loadmat("/user/chae2089/CWpaper/FN_REVISION/feature_for_2nd_model/eeg_alone_str/subject{}.mat".format(control_num[n]))
                #test_data = loadmat("/user/chae2089/CWpaper/FINAL/2nd_model/feature_nrem_rem_str/feature/subject{}.mat".format(control_num[n]))
                test_data = np.transpose(test_data['nrem_rem_all'])
                test_set = np.append(test_set, test_data, 0)
                test_set_label = np.append(test_set_label, test_label, 0)
                
#             elif np.isin(mtom,control_num[n]).sum() == 1:
#                 test_label = np.array([[2]])
#                 test_data = loadmat("/user/chae2089/CWpaper/FN_REVISION/feature_for_2nd_model/eeg_alone_str/subject{}.mat".format(control_num[n]))
#                 #test_data = loadmat("/user/chae2089/CWpaper/FINAL/2nd_model/feature_nrem_rem_str/feature/subject{}.mat".format(control_num[n]))
#                 test_data = np.transpose(test_data['nrem_rem_all'])
#                 test_set = np.append(test_set, test_data, 0) 
#                 test_set_label = np.append(test_set_label, test_label, 0)
                
            elif np.isin(severe,control_num[n]).sum() == 1:
                test_label = np.array([[2]])
                test_data = loadmat("/user/chae2089/CWpaper/FN_REVISION/feature_for_2nd_model/eeg_alone_str/subject{}.mat".format(control_num[n]))
                #test_data = loadmat("/user/chae2089/CWpaper/FINAL/2nd_model/feature_nrem_rem_str/feature/subject{}.mat".format(control_num[n]))
                test_data = np.transpose(test_data['nrem_rem_all'])
                test_set = np.append(test_set, test_data, 0) 
                test_set_label = np.append(test_set_label, test_label, 0)
            
        for m in train:
                        
            train_label = np.empty((0,1))
            if np.isin(normal,control_num[m]).sum() == 1:
                train_label = np.array([[1]])
                train_data = loadmat("/user/chae2089/CWpaper/FN_REVISION/feature_for_2nd_model/eeg_alone_str/subject{}".format(control_num[m]))
                #train_data = loadmat("/user/chae2089/CWpaper/FINAL/2nd_model/feature_nrem_rem_str/feature/subject{}".format(control_num[m]))
                train_data = np.transpose(train_data['nrem_rem_all'])
                train_set = np.append(train_set, train_data, 0)
                train_set_label = np.append(train_set_label, train_label, 0)
            
#             elif np.isin(mtom,control_num[m]).sum() == 1:
#                 train_label = np.array([[2]])
#                 train_data = loadmat("/user/chae2089/CWpaper/FN_REVISION/feature_for_2nd_model/eeg_alone_str/subject{}".format(control_num[m]))
#                 #train_data = loadmat("/user/chae2089/CWpaper/FINAL/2nd_model/feature_nrem_rem_str/feature/subject{}".format(control_num[m]))
#                 train_data = np.transpose(train_data['nrem_rem_all'])
#                 train_set = np.append(train_set, train_data, 0)
#                 train_set_label = np.append(train_set_label, train_label, 0)
                
            elif np.isin(severe,control_num[m]).sum() == 1:
                train_label = np.array([[2]])
                train_data = loadmat("/user/chae2089/CWpaper/FN_REVISION/feature_for_2nd_model/eeg_alone_str/subject{}".format(control_num[m]))
                #train_data = loadmat("/user/chae2089/CWpaper/FINAL/2nd_model/feature_nrem_rem_str/feature/subject{}".format(control_num[m]))
                train_data = np.transpose(train_data['nrem_rem_all'])
                train_set = np.append(train_set, train_data, 0)
                train_set_label = np.append(train_set_label, train_label, 0)  
                
        train_set2 = train_set
        train_set_label2 = train_set_label.ravel()
    
        #test_set = np.transpose(test_set)
        #test_set_label = np.transpose(test_set_label)
        
        param_grid = {'n_neighbors': [1,3,5,7,9,11,13,15,17,19], 'weights' : ['uniform','distance'], 'metric' : ['euclidean','manhattan']}
        clf_grid = GridSearchCV(KNeighborsClassifier(), param_grid) 
        clf_grid.fit(train_set2, train_set_label2)
        n_neighbors_best = clf_grid.best_params_["n_neighbors"]
        weights_best = clf_grid.best_params_["weights"]
        metric_best = clf_grid.best_params_["metric"]
        
        print(n_neighbors_best,weights_best, metric_best)

        model = KNeighborsClassifier(n_neighbors=n_neighbors_best, weights=weights_best, metric=metric_best)
        model.fit(train_set2, train_set_label2)
        
        pred = model.predict(test_set)
                
            
        result=confusion_matrix(test_set_label,pred)
        print(result)
        result2=result2 + result
        
        accuracy = np.round(accuracy_score(test_set_label,pred), 4)
        accuracy2.append(accuracy)
        
                 
                
        num = num+1
        

0번째 아우터 루프의 1번째 테스트 인덱스
[ 6  7 12 14 16 18 28 35 40 51 52]
0번째 아우터 루프의 1번째 트레인 인덱스 
[ 0  1  2  3  4  5  8  9 10 11 13 15 17 19 20 21 22 23 24 25 26 27 29 30
 31 32 33 34 36 37 38 39 41 42 43 44 45 46 47 48 49 50 53 54]


3 uniform euclidean
[[3 1]
 [0 4]]
0번째 아우터 루프의 2번째 테스트 인덱스
[ 0  5 10 11 17 20 27 30 34 43 50]
0번째 아우터 루프의 2번째 트레인 인덱스 
[ 1  2  3  4  6  7  8  9 12 13 14 15 16 18 19 21 22 23 24 25 26 28 29 31
 32 33 35 36 37 38 39 40 41 42 44 45 46 47 48 49 51 52 53 54]


5 uniform euclidean
[[4 0]
 [0 3]]
0번째 아우터 루프의 3번째 테스트 인덱스
[ 2  8  9 23 25 32 36 44 45 49 54]
0번째 아우터 루프의 3번째 트레인 인덱스 
[ 0  1  3  4  5  6  7 10 11 12 13 14 15 16 17 18 19 20 21 22 24 26 27 28
 29 30 31 33 34 35 37 38 39 40 41 42 43 46 47 48 50 51 52 53]


11 uniform euclidean
[[3 0]
 [3 2]]
0번째 아우터 루프의 4번째 테스트 인덱스
[ 1  4 15 21 26 29 33 41 42 47 48]
0번째 아우터 루프의 4번째 트레인 인덱스 
[ 0  2  3  5  6  7  8  9 10 11 12 13 14 16 17 18 19 20 22 23 24 25 27 28
 30 31 32 34 35 36 37 38 39 40 43 44 45 46 49 50 51 52 53 54]


3 uniform 

17 distance euclidean
[[3 2]
 [0 4]]
6번째 아우터 루프의 4번째 테스트 인덱스
[ 3  4  8 14 16 18 25 41 47 51 54]
6번째 아우터 루프의 4번째 트레인 인덱스 
[ 0  1  2  5  6  7  9 10 11 12 13 15 17 19 20 21 22 23 24 26 27 28 29 30
 31 32 33 34 35 36 37 38 39 40 42 43 44 45 46 48 49 50 52 53]


1 uniform euclidean
[[2 2]
 [1 3]]
6번째 아우터 루프의 5번째 테스트 인덱스
[ 0 10 27 29 31 34 35 37 39 40 42]
6번째 아우터 루프의 5번째 트레인 인덱스 
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 28 30 32 33 36 38 41 43 44 45 46 47 48 49 50 51 52 53 54]


11 uniform euclidean
[[2 0]
 [1 5]]
7번째 아우터 루프의 1번째 테스트 인덱스
[ 0  3  4  5 13 17 18 35 40 42 45]
7번째 아우터 루프의 1번째 트레인 인덱스 
[ 1  2  6  7  8  9 10 11 12 14 15 16 19 20 21 22 23 24 25 26 27 28 29 30
 31 32 33 34 36 37 38 39 41 43 44 46 47 48 49 50 51 52 53 54]


1 uniform euclidean
[[4 1]
 [0 4]]
7번째 아우터 루프의 2번째 테스트 인덱스
[ 2  7 27 30 31 36 41 48 51 52 53]
7번째 아우터 루프의 2번째 트레인 인덱스 
[ 0  1  3  4  5  6  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 28 29 32 33 34 35 37 38 39 40 42 

In [5]:
print(result2)
print(np.mean(accuracy2))
print(np.std(accuracy2))
print(accuracy2)

[[125.  35.]
 [ 43. 167.]]
0.7903119999999998
0.1386648803987513
[0.875, 1.0, 0.625, 0.7143, 0.8571, 0.8, 1.0, 0.8889, 0.8571, 0.8889, 0.875, 0.7143, 0.6667, 0.8571, 0.8333, 0.625, 1.0, 0.8, 0.875, 0.6667, 0.8571, 0.8889, 0.75, 0.5556, 0.75, 0.8333, 0.625, 1.0, 0.7778, 0.75, 0.8333, 0.6667, 0.7778, 0.625, 0.875, 0.8889, 0.875, 0.6667, 0.6, 1.0, 1.0, 0.6667, 0.6667, 0.6667, 0.8, 0.4286, 1.0, 0.7, 0.5714, 1.0]
