In [1]:
import os
import pandas as pd
import numpy as np
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from scipy.io import loadmat, savemat
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
import random
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

In [2]:
p_num=56
a = []

for i in range(10):
    a.append(np.ceil((np.random.permutation(p_num)+1)/(p_num/5.0)).reshape(1,p_num))

a = np.array(a)
len(a)

10

In [3]:
normal_Y=np.array([35,45,55,65,83,104,106,108,110,112,126,137,151,154,163,26,53,105]);
normal_O=np.array([1,12,14,20,41,62,77,133,153,15,42,44,64,89,160,161]);
 
mtom_Y=np.array([25,47,50,56,59,63,92,111,51,58,94,102,114,144,122,38,68,91,95,98,138]);
mtom_O=np.array([2,4,96,118,125,142,21,67,101,115,127,136,99,116,130,11,49,82]);
 
severe_Y=np.array([24,28,31,34,36,40,60,76,128,135,57,66,71,79,109,139,152]);
severe_O=np.array([30,43,46,69,70,73,75,86,97,117,129,131,134,156,162,19,23,74,78,84,85]);

normal=np.array([35,45,55,65,83,104,106,108,110,112,126,137,151,154,163,26,53,105,
                 1,12,14,20,41,62,77,133,153,15,42,44,64,89,160,161]);
mtom=np.array([25,47,50,56,59,63,92,111,51,58,94,102,114,144,122,38,68,91,95,98,138,
               2,4,96,118,125,142,21,67,101,115,127,136,99,116,130,11,49,82]);
severe=np.array([24,28,31,34,36,40,60,76,128,135,57,66,71,79,109,139,152,
                 30,43,46,69,70,73,75,86,97,117,129,131,134,156,162,19,23,74,78,84,85]);

control_num=np.array([35,45,55,65,83,104,106,108,110,112,126,137,151,154,163,26,53,105,
                     25,47,50,56,59,63,92,111,51,58,94,102,114,144,122,38,68,91,95,98,138,
                     24,28,31,34,36,40,60,76,128,135,57,66,71,79,109,139,152]);


Old=np.array([1,12,14,20,41,62,77,133,153,15,42,44,64,89,160,161,
             2,4,96,118,125,142,21,67,101,115,127,136,99,116,130,11,49,82,
             30,43,46,69,70,73,75,86,97,117,129,131,134,156,162,19,23,74,78,84,85]);

len(control_num)

56

In [4]:
num = 0
accuracy2 =[]
feature_num=102 #97
result2 = np.zeros((3,3)) #

for k in range(len(a)):
    b = a[k]
    
    for m in range(1,6):
        index_test = np.where(b == m)
        index_train = np.where(b != m)
        
        test_set = np.empty((0,feature_num))
        train_set = np.empty((0,feature_num))
        test_set_label = np.empty((0,1))
        train_set_label = np.empty((0,1))
        train_set2 = np.empty((0,feature_num))
        test_set_label2 = np.empty((0,1))
        
        test = index_test[1]
        train = index_train[1]
        
        print("{}번째 아우터 루프의 {}번째 테스트 인덱스".format(k, m))
        print(test)
        print("{}번째 아우터 루프의 {}번째 트레인 인덱스 ".format(k, m))
        print(train)
        print("\n")
        
        for n in test:
                        
            test_label = np.empty((0,1))
            if np.isin(normal,control_num[n]).sum() == 1:
                test_label = np.array([[1]])
                test_data = loadmat("/user/chae2089/CWpaper/FN_REVISION/feature_for_2nd_model/eeg_combined_spo2_str/subject{}.mat".format(control_num[n]))
                #test_data = loadmat("/user/chae2089/CWpaper/FINAL/2nd_model/feature_nrem_rem_str/feature/subject{}.mat".format(control_num[n]))
                test_data = np.transpose(test_data['nrem_rem_all_comb_spo2'])
                test_set = np.append(test_set, test_data, 0)
                test_set_label = np.append(test_set_label, test_label, 0)
                
            elif np.isin(mtom,control_num[n]).sum() == 1:
                test_label = np.array([[2]])
                test_data = loadmat("/user/chae2089/CWpaper/FN_REVISION/feature_for_2nd_model/eeg_combined_spo2_str/subject{}.mat".format(control_num[n]))
                #test_data = loadmat("/user/chae2089/CWpaper/FINAL/2nd_model/feature_nrem_rem_str/feature/subject{}.mat".format(control_num[n]))
                test_data = np.transpose(test_data['nrem_rem_all_comb_spo2'])
                test_set = np.append(test_set, test_data, 0) 
                test_set_label = np.append(test_set_label, test_label, 0)
                
            elif np.isin(severe,control_num[n]).sum() == 1:
                test_label = np.array([[3]])
                test_data = loadmat("/user/chae2089/CWpaper/FN_REVISION/feature_for_2nd_model/eeg_combined_spo2_str/subject{}.mat".format(control_num[n]))
                #test_data = loadmat("/user/chae2089/CWpaper/FINAL/2nd_model/feature_nrem_rem_str/feature/subject{}.mat".format(control_num[n]))
                test_data = np.transpose(test_data['nrem_rem_all_comb_spo2'])
                test_set = np.append(test_set, test_data, 0) 
                test_set_label = np.append(test_set_label, test_label, 0)
            
        for m in train:
                        
            train_label = np.empty((0,1))
            if np.isin(normal,control_num[m]).sum() == 1:
                train_label = np.array([[1]])
                train_data = loadmat("/user/chae2089/CWpaper/FN_REVISION/feature_for_2nd_model/eeg_combined_spo2_str/subject{}".format(control_num[m]))
                #train_data = loadmat("/user/chae2089/CWpaper/FINAL/2nd_model/feature_nrem_rem_str/feature/subject{}".format(control_num[m]))
                train_data = np.transpose(train_data['nrem_rem_all_comb_spo2'])
                train_set = np.append(train_set, train_data, 0)
                train_set_label = np.append(train_set_label, train_label, 0)
            
            elif np.isin(mtom,control_num[m]).sum() == 1:
                train_label = np.array([[2]])
                train_data = loadmat("/user/chae2089/CWpaper/FN_REVISION/feature_for_2nd_model/eeg_combined_spo2_str/subject{}".format(control_num[m]))
                #train_data = loadmat("/user/chae2089/CWpaper/FINAL/2nd_model/feature_nrem_rem_str/feature/subject{}".format(control_num[m]))
                train_data = np.transpose(train_data['nrem_rem_all_comb_spo2'])
                train_set = np.append(train_set, train_data, 0)
                train_set_label = np.append(train_set_label, train_label, 0)
                
            elif np.isin(severe,control_num[m]).sum() == 1:
                train_label = np.array([[3]])
                train_data = loadmat("/user/chae2089/CWpaper/FN_REVISION/feature_for_2nd_model/eeg_combined_spo2_str/subject{}".format(control_num[m]))
                #train_data = loadmat("/user/chae2089/CWpaper/FINAL/2nd_model/feature_nrem_rem_str/feature/subject{}".format(control_num[m]))
                train_data = np.transpose(train_data['nrem_rem_all_comb_spo2'])
                train_set = np.append(train_set, train_data, 0)
                train_set_label = np.append(train_set_label, train_label, 0)  
                
        train_set2 = train_set
        train_set_label2 = train_set_label.ravel()
    
        #test_set = np.transpose(test_set)
        #test_set_label = np.transpose(test_set_label)
        
        param_grid = {'hidden_layer_sizes':[(16,),(32,),(64,),
                                           (16,16,),(32,16,),(64,16,),
                                           (16,32,),(32,32,),(64,32,),
                                           (16,64,),(32,64,),(64,64,)]}
        
        clf_grid = GridSearchCV(MLPClassifier(max_iter=200,activation='relu', solver='adam', random_state=1), param_grid) 
        clf_grid.fit(train_set2, train_set_label2)
        hidden_layer_sizes_best = clf_grid.best_params_["hidden_layer_sizes"]
                
        print(hidden_layer_sizes_best)

        model = MLPClassifier(max_iter=200, activation='relu', solver='adam', random_state=1, hidden_layer_sizes=hidden_layer_sizes_best)
        model.fit(train_set2, train_set_label2)
                
        pred = model.predict(test_set)    
                
            
        result=confusion_matrix(test_set_label,pred)
        print(result)
        result2=result2 + result
        
        accuracy = np.round(accuracy_score(test_set_label,pred), 4)
        accuracy2.append(accuracy)
        
                 
                
        num = num+1
        

0번째 아우터 루프의 1번째 테스트 인덱스
[ 2  4  5  8  9 17 27 36 39 41 53]
0번째 아우터 루프의 1번째 트레인 인덱스 
[ 0  1  3  6  7 10 11 12 13 14 15 16 18 19 20 21 22 23 24 25 26 28 29 30
 31 32 33 34 35 37 38 40 42 43 44 45 46 47 48 49 50 51 52 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(32,)
[[1 5 0]
 [0 2 0]
 [0 2 1]]
0번째 아우터 루프의 2번째 테스트 인덱스
[ 0 11 13 14 16 22 29 33 44 45 55]
0번째 아우터 루프의 2번째 트레인 인덱스 
[ 1  2  3  4  5  6  7  8  9 10 12 15 17 18 19 20 21 23 24 25 26 27 28 30
 31 32 34 35 36 37 38 39 40 41 42 43 46 47 48 49 50 51 52 53 54]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(32,)
[[3 1 1]
 [1 1 1]
 [0 1 2]]
0번째 아우터 루프의 3번째 테스트 인덱스
[ 1  7 18 23 24 28 30 38 47 48 52]
0번째 아우터 루프의 3번째 트레인 인덱스 
[ 0  2  3  4  5  6  8  9 10 11 12 13 14 15 16 17 19 20 21 22 25 26 27 29
 31 32 33 34 35 36 37 39 40 41 42 43 44 45 46 49 50 51 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(64, 64)


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[2 0 0]
 [1 3 2]
 [0 2 1]]
0번째 아우터 루프의 4번째 테스트 인덱스
[ 6 15 20 31 32 34 35 37 43 49 54]
0번째 아우터 루프의 4번째 트레인 인덱스 
[ 0  1  2  3  4  5  7  8  9 10 11 12 13 14 16 17 18 19 21 22 23 24 25 26
 27 28 29 30 33 36 38 39 40 41 42 44 45 46 47 48 50 51 52 53 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(64, 64)


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[2 0 0]
 [3 3 0]
 [2 0 1]]
0번째 아우터 루프의 5번째 테스트 인덱스
[ 3 10 12 19 21 25 26 40 42 46 50 51]
0번째 아우터 루프의 5번째 트레인 인덱스 
[ 0  1  2  4  5  6  7  8  9 11 13 14 15 16 17 18 20 22 23 24 27 28 29 30
 31 32 33 34 35 36 37 38 39 41 43 44 45 47 48 49 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[2 1 0]
 [0 4 0]
 [0 0 5]]
1번째 아우터 루프의 1번째 테스트 인덱스
[ 1  7 11 21 24 36 38 43 44 45 48]
1번째 아우터 루프의 1번째 트레인 인덱스 
[ 0  2  3  4  5  6  8  9 10 12 13 14 15 16 17 18 19 20 22 23 25 26 27 28
 29 30 31 32 33 34 35 37 39 40 41 42 46 47 49 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[3 0 0]
 [1 2 1]
 [0 3 1]]
1번째 아우터 루프의 2번째 테스트 인덱스
[14 26 31 32 33 37 39 41 42 49 55]
1번째 아우터 루프의 2번째 트레인 인덱스 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 15 16 17 18 19 20 21 22 23 24
 25 27 28 29 30 34 35 36 38 40 43 44 45 46 47 48 50 51 52 53 54]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[1 0 0]
 [2 2 1]
 [1 0 4]]
1번째 아우터 루프의 3번째 테스트 인덱스
[10 13 15 19 23 25 30 47 50 51 54]
1번째 아우터 루프의 3번째 트레인 인덱스 
[ 0  1  2  3  4  5  6  7  8  9 11 12 14 16 17 18 20 21 22 24 26 27 28 29
 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 48 49 52 53 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[3 0 0]
 [0 4 0]
 [1 0 3]]
1번째 아우터 루프의 4번째 테스트 인덱스
[ 2  6  8 16 18 28 34 35 46 52 53]
1번째 아우터 루프의 4번째 트레인 인덱스 
[ 0  1  3  4  5  7  9 10 11 12 13 14 15 17 19 20 21 22 23 24 25 26 27 29
 30 31 32 33 36 37 38 39 40 41 42 43 44 45 47 48 49 50 51 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[3 0 1]
 [0 4 0]
 [0 0 3]]
1번째 아우터 루프의 5번째 테스트 인덱스
[ 0  3  4  5  9 12 17 20 22 27 29 40]
1번째 아우터 루프의 5번째 트레인 인덱스 
[ 1  2  6  7  8 10 11 13 14 15 16 18 19 21 23 24 25 26 28 30 31 32 33 34
 35 36 37 38 39 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(32,)
[[2 5 0]
 [1 3 0]
 [0 0 1]]
2번째 아우터 루프의 1번째 테스트 인덱스
[ 0  1  4 18 22 23 28 30 32 34 37]
2번째 아우터 루프의 1번째 트레인 인덱스 
[ 2  3  5  6  7  8  9 10 11 12 13 14 15 16 17 19 20 21 24 25 26 27 29 31
 33 35 36 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[3 0 0]
 [3 3 2]
 [0 0 0]]
2번째 아우터 루프의 2번째 테스트 인덱스
[ 2  3  6 10 14 16 20 27 35 40 44]
2번째 아우터 루프의 2번째 트레인 인덱스 
[ 0  1  4  5  7  8  9 11 12 13 15 17 18 19 21 22 23 24 25 26 28 29 30 31
 32 33 34 36 37 38 39 41 42 43 45 46 47 48 49 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(32,)
[[3 2 1]
 [0 3 0]
 [0 0 2]]
2번째 아우터 루프의 3번째 테스트 인덱스
[ 7  8  9 11 15 17 21 25 39 45 49]
2번째 아우터 루프의 3번째 트레인 인덱스 
[ 0  1  2  3  4  5  6 10 12 13 14 16 18 19 20 22 23 24 26 27 28 29 30 31
 32 33 34 35 36 37 38 40 41 42 43 44 46 47 48 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(32,)
[[4 2 0]
 [0 2 0]
 [0 2 1]]
2번째 아우터 루프의 4번째 테스트 인덱스
[12 13 19 26 31 47 48 51 52 53 55]
2번째 아우터 루프의 4번째 트레인 인덱스 
[ 0  1  2  3  4  5  6  7  8  9 10 11 14 15 16 17 18 20 21 22 23 24 25 27
 28 29 30 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 49 50 54]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[2 0 0]
 [0 3 0]
 [0 4 2]]
2번째 아우터 루프의 5번째 테스트 인덱스
[ 5 24 29 33 36 38 41 42 43 46 50 54]
2번째 아우터 루프의 5번째 트레인 인덱스 
[ 0  1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 25
 26 27 28 30 31 32 34 35 37 39 40 44 45 47 48 49 51 52 53 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[1 0 0]
 [1 2 2]
 [2 1 3]]
3번째 아우터 루프의 1번째 테스트 인덱스
[ 0  2  3 10 13 15 30 33 41 42 52]
3번째 아우터 루프의 1번째 트레인 인덱스 
[ 1  4  5  6  7  8  9 11 12 14 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 31 32 34 35 36 37 38 39 40 43 44 45 46 47 48 49 50 51 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[1 5 0]
 [0 1 1]
 [0 1 2]]
3번째 아우터 루프의 2번째 테스트 인덱스
[11 14 17 18 22 26 32 34 37 38 45]
3번째 아우터 루프의 2번째 트레인 인덱스 
[ 0  1  2  3  4  5  6  7  8  9 10 12 13 15 16 19 20 21 23 24 25 27 28 29
 30 31 33 35 36 39 40 41 42 43 44 46 47 48 49 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[3 0 0]
 [3 3 1]
 [0 0 1]]
3번째 아우터 루프의 3번째 테스트 인덱스
[ 1  5  6  7 12 24 29 40 49 50 53]
3번째 아우터 루프의 3번째 트레인 인덱스 
[ 0  2  3  4  8  9 10 11 13 14 15 16 17 18 19 20 21 22 23 25 26 27 28 30
 31 32 33 34 35 36 37 38 39 41 42 43 44 45 46 47 48 51 52 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[4 1 0]
 [0 1 1]
 [0 0 4]]
3번째 아우터 루프의 4번째 테스트 인덱스
[ 4  8 19 20 25 28 35 39 44 46 55]
3번째 아우터 루프의 4번째 트레인 인덱스 
[ 0  1  2  3  5  6  7  9 10 11 12 13 14 15 16 17 18 21 22 23 24 26 27 29
 30 31 32 33 34 36 37 38 40 41 42 43 45 47 48 49 50 51 52 53 54]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[2 0 0]
 [0 4 1]
 [0 0 4]]
3번째 아우터 루프의 5번째 테스트 인덱스
[ 9 16 21 23 27 31 36 43 47 48 51 54]
3번째 아우터 루프의 5번째 트레인 인덱스 
[ 0  1  2  3  4  5  6  7  8 10 11 12 13 14 15 17 18 19 20 22 24 25 26 28
 29 30 32 33 34 35 37 38 39 40 41 42 44 45 46 49 50 52 53 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[2 0 0]
 [1 4 0]
 [2 2 1]]
4번째 아우터 루프의 1번째 테스트 인덱스
[ 5  7 21 26 30 33 35 38 41 42 44]
4번째 아우터 루프의 1번째 트레인 인덱스 
[ 0  1  2  3  4  6  8  9 10 11 12 13 14 15 16 17 18 19 20 22 23 24 25 27
 28 29 31 32 34 36 37 39 40 43 45 46 47 48 49 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[2 0 0]
 [2 2 2]
 [1 0 2]]
4번째 아우터 루프의 2번째 테스트 인덱스
[ 1  3  6 14 15 25 36 37 47 48 53]
4번째 아우터 루프의 2번째 트레인 인덱스 
[ 0  2  4  5  7  8  9 10 11 12 13 16 17 18 19 20 21 22 23 24 26 27 28 29
 30 31 32 33 34 35 38 39 40 41 42 43 44 45 46 49 50 51 52 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[4 1 0]
 [0 3 0]
 [0 1 2]]
4번째 아우터 루프의 3번째 테스트 인덱스
[ 2  8 17 18 20 28 29 32 39 43 46]
4번째 아우터 루프의 3번째 트레인 인덱스 
[ 0  1  3  4  5  6  7  9 10 11 12 13 14 15 16 19 21 22 23 24 25 26 27 30
 31 33 34 35 36 37 38 40 41 42 44 45 47 48 49 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[3 0 0]
 [2 3 0]
 [1 0 2]]
4번째 아우터 루프의 4번째 테스트 인덱스
[ 4  9 10 13 19 22 24 27 51 52 55]
4번째 아우터 루프의 4번째 트레인 인덱스 
[ 0  1  2  3  5  6  7  8 11 12 14 15 16 17 18 20 21 23 25 26 28 29 30 31
 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 53 54]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[3 1 0]
 [1 2 1]
 [0 0 3]]
4번째 아우터 루프의 5번째 테스트 인덱스
[ 0 11 12 16 23 31 34 40 45 49 50 54]
4번째 아우터 루프의 5번째 트레인 인덱스 
[ 1  2  3  4  5  6  7  8  9 10 13 14 15 17 18 19 20 21 22 24 25 26 27 28
 29 30 32 33 35 36 37 38 39 41 42 43 44 46 47 48 51 52 53 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[3 1 0]
 [0 3 0]
 [1 2 2]]
5번째 아우터 루프의 1번째 테스트 인덱스
[ 0  2  5 10 11 14 17 23 25 26 47]
5번째 아우터 루프의 1번째 트레인 인덱스 
[ 1  3  4  6  7  8  9 12 13 15 16 18 19 20 21 22 24 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 48 49 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(32,)
[[4 3 0]
 [0 3 0]
 [0 0 1]]
5번째 아우터 루프의 2번째 테스트 인덱스
[ 1  3  7  8 15 18 21 39 44 46 54]
5번째 아우터 루프의 2번째 트레인 인덱스 
[ 0  2  4  5  6  9 10 11 12 13 14 16 17 19 20 22 23 24 25 26 27 28 29 30
 31 32 33 34 35 36 37 38 40 41 42 43 45 47 48 49 50 51 52 53 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(32,)
[[3 2 0]
 [0 2 0]
 [1 0 3]]
5번째 아우터 루프의 3번째 테스트 인덱스
[ 4  9 20 22 24 28 34 37 43 52 53]
5번째 아우터 루프의 3번째 트레인 인덱스 
[ 0  1  2  3  5  6  7  8 10 11 12 13 14 15 16 17 18 19 21 23 25 26 27 29
 30 31 32 33 35 36 38 39 40 41 42 44 45 46 47 48 49 50 51 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[2 0 0]
 [3 2 1]
 [1 0 2]]
5번째 아우터 루프의 4번째 테스트 인덱스
[ 6 12 16 27 29 30 31 35 41 42 55]
5번째 아우터 루프의 4번째 트레인 인덱스 
[ 0  1  2  3  4  5  7  8  9 10 11 13 14 15 17 18 19 20 21 22 23 24 25 26
 28 32 33 34 36 37 38 39 40 43 44 45 46 47 48 49 50 51 52 53 54]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[2 1 0]
 [1 4 0]
 [0 1 2]]
5번째 아우터 루프의 5번째 테스트 인덱스
[13 19 32 33 36 38 40 45 48 49 50 51]
5번째 아우터 루프의 5번째 트레인 인덱스 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 14 15 16 17 18 20 21 22 23 24 25
 26 27 28 29 30 31 34 35 37 39 41 42 43 44 46 47 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[1 0 0]
 [2 2 1]
 [0 2 4]]
6번째 아우터 루프의 1번째 테스트 인덱스
[10 13 15 16 20 24 29 38 43 51 53]
6번째 아우터 루프의 1번째 트레인 인덱스 
[ 0  1  2  3  4  5  6  7  8  9 11 12 14 17 18 19 21 22 23 25 26 27 28 30
 31 32 33 34 35 36 37 39 40 41 42 44 45 46 47 48 49 50 52 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[3 0 1]
 [0 2 2]
 [0 1 2]]
6번째 아우터 루프의 2번째 테스트 인덱스
[ 4  9 12 19 21 23 28 31 34 36 45]
6번째 아우터 루프의 2번째 트레인 인덱스 
[ 0  1  2  3  5  6  7  8 10 11 13 14 15 16 17 18 20 22 24 25 26 27 29 30
 32 33 35 37 38 39 40 41 42 43 44 46 47 48 49 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[3 0 0]
 [0 5 2]
 [0 0 1]]
6번째 아우터 루프의 3번째 테스트 인덱스
[ 7 22 26 41 44 46 49 50 52 54 55]
6번째 아우터 루프의 3번째 트레인 인덱스 
[ 0  1  2  3  4  5  6  8  9 10 11 12 13 14 15 16 17 18 19 20 21 23 24 25
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 42 43 45 47 48 51 53]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[1 0 0]
 [1 1 0]
 [2 4 2]]
6번째 아우터 루프의 4번째 테스트 인덱스
[ 0  1  3 11 14 25 27 32 35 37 47]
6번째 아우터 루프의 4번째 트레인 인덱스 
[ 2  4  5  6  7  8  9 10 12 13 15 16 17 18 19 20 21 22 23 24 26 28 29 30
 31 33 34 36 38 39 40 41 42 43 44 45 46 48 49 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[3 2 0]
 [1 3 1]
 [0 0 1]]
6번째 아우터 루프의 5번째 테스트 인덱스
[ 2  5  6  8 17 18 30 33 39 40 42 48]
6번째 아우터 루프의 5번째 트레인 인덱스 
[ 0  1  3  4  7  9 10 11 12 13 14 15 16 19 20 21 22 23 24 25 26 27 28 29
 31 32 34 35 36 37 38 41 43 44 45 46 47 49 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(32,)
[[2 3 0]
 [0 2 1]
 [0 1 3]]
7번째 아우터 루프의 1번째 테스트 인덱스
[ 2  5  7 12 14 19 28 31 36 39 41]
7번째 아우터 루프의 1번째 트레인 인덱스 
[ 0  1  3  4  6  8  9 10 11 13 15 16 17 18 20 21 22 23 24 25 26 27 29 30
 32 33 34 35 37 38 40 42 43 44 45 46 47 48 49 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[5 0 0]
 [0 3 1]
 [0 1 1]]
7번째 아우터 루프의 2번째 테스트 인덱스
[ 4  6 10 15 16 17 27 47 51 52 53]
7번째 아우터 루프의 2번째 트레인 인덱스 
[ 0  1  2  3  5  7  8  9 11 12 13 14 18 19 20 21 22 23 24 25 26 28 29 30
 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 48 49 50 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(32,)
[[3 3 0]
 [0 1 0]
 [0 2 2]]
7번째 아우터 루프의 3번째 테스트 인덱스
[ 0  8 24 25 32 40 42 48 50 54 55]
7번째 아우터 루프의 3번째 트레인 인덱스 
[ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 26 27
 28 29 30 31 33 34 35 36 37 38 39 41 43 44 45 46 47 49 51 52 53]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[2 0 0]
 [1 2 0]
 [1 1 4]]
7번째 아우터 루프의 4번째 테스트 인덱스
[ 1 13 20 21 26 29 33 37 44 46 49]
7번째 아우터 루프의 4번째 트레인 인덱스 
[ 0  2  3  4  5  6  7  8  9 10 11 12 14 15 16 17 18 19 22 23 24 25 27 28
 30 31 32 34 35 36 38 39 40 41 42 43 45 47 48 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(64, 64)


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[2 0 0]
 [1 3 2]
 [0 0 3]]
7번째 아우터 루프의 5번째 테스트 인덱스
[ 3  9 11 18 22 23 30 34 35 38 43 45]
7번째 아우터 루프의 5번째 트레인 인덱스 
[ 0  1  2  4  5  6  7  8 10 12 13 14 15 16 17 19 20 21 24 25 26 27 28 29
 31 32 33 36 37 39 40 41 42 44 46 47 48 49 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(64, 64)


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[3 0 0]
 [2 5 0]
 [1 1 0]]
8번째 아우터 루프의 1번째 테스트 인덱스
[ 2  3  6  9 15 20 29 31 34 49 50]
8번째 아우터 루프의 1번째 트레인 인덱스 
[ 0  1  4  5  7  8 10 11 12 13 14 16 17 18 19 21 22 23 24 25 26 27 28 30
 32 33 35 36 37 38 39 40 41 42 43 44 45 46 47 48 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[3 2 0]
 [0 4 0]
 [0 0 2]]
8번째 아우터 루프의 2번째 테스트 인덱스
[ 1  4  8 12 14 16 17 18 37 39 45]
8번째 아우터 루프의 2번째 트레인 인덱스 
[ 0  2  3  5  6  7  9 10 11 13 15 19 20 21 22 23 24 25 26 27 28 29 30 31
 32 33 34 35 36 38 40 41 42 43 44 46 47 48 49 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(32,)
[[2 4 1]
 [0 2 0]
 [0 1 1]]
8번째 아우터 루프의 3번째 테스트 인덱스
[13 25 26 27 28 36 38 46 47 48 52]
8번째 아우터 루프의 3번째 트레인 인덱스 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 14 15 16 17 18 19 20 21 22 23 24
 29 30 31 32 33 34 35 37 39 40 41 42 43 44 45 49 50 51 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[1 0 0]
 [0 6 0]
 [0 1 3]]
8번째 아우터 루프의 4번째 테스트 인덱스
[10 19 23 24 30 32 35 40 41 42 53]
8번째 아우터 루프의 4번째 트레인 인덱스 
[ 0  1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 20 21 22 25 26 27
 28 29 31 33 34 36 37 38 39 43 44 45 46 47 48 49 50 51 52 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[1 0 0]
 [2 3 1]
 [1 0 3]]
8번째 아우터 루프의 5번째 테스트 인덱스
[ 0  5  7 11 21 22 33 43 44 51 54 55]
8번째 아우터 루프의 5번째 트레인 인덱스 
[ 1  2  3  4  6  8  9 10 12 13 14 15 16 17 18 19 20 23 24 25 26 27 28 29
 30 31 32 34 35 36 37 38 39 40 41 42 45 46 47 48 49 50 52 53]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[3 1 0]
 [1 1 1]
 [1 1 3]]
9번째 아우터 루프의 1번째 테스트 인덱스
[ 8 20 25 31 35 38 40 46 50 51 53]
9번째 아우터 루프의 1번째 트레인 인덱스 
[ 0  1  2  3  4  5  6  7  9 10 11 12 13 14 15 16 17 18 19 21 22 23 24 26
 27 28 29 30 32 33 34 36 37 39 41 42 43 44 45 47 48 49 52 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[1 0 0]
 [2 3 0]
 [0 0 5]]
9번째 아우터 루프의 2번째 테스트 인덱스
[ 3 23 24 27 28 34 41 44 45 49 52]
9번째 아우터 루프의 2번째 트레인 인덱스 
[ 0  1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 25 26
 29 30 31 32 33 35 36 37 38 39 40 42 43 46 47 48 50 51 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[1 0 0]
 [0 4 1]
 [1 2 2]]
9번째 아우터 루프의 3번째 테스트 인덱스
[ 1  2  5  6 10 17 19 22 33 48 54]
9번째 아우터 루프의 3번째 트레인 인덱스 
[ 0  3  4  7  8  9 11 12 13 14 15 16 18 20 21 23 24 25 26 27 28 29 30 31
 32 34 35 36 37 38 39 40 41 42 43 44 45 46 47 49 50 51 52 53 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(32,)
[[4 2 0]
 [1 1 1]
 [1 0 1]]
9번째 아우터 루프의 4번째 테스트 인덱스
[ 0  4  7  9 16 26 30 36 39 42 55]
9번째 아우터 루프의 4번째 트레인 인덱스 
[ 1  2  3  5  6  8 10 11 12 13 14 15 17 18 19 20 21 22 23 24 25 27 28 29
 31 32 33 34 35 37 38 40 41 43 44 45 46 47 48 49 50 51 52 53 54]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(16, 32)
[[2 3 0]
 [0 3 0]
 [0 0 3]]
9번째 아우터 루프의 5번째 테스트 인덱스
[11 12 13 14 15 18 21 29 32 37 43 47]
9번째 아우터 루프의 5번째 트레인 인덱스 
[ 0  1  2  3  4  5  6  7  8  9 10 16 17 19 20 22 23 24 25 26 27 28 30 31
 33 34 35 36 38 39 40 41 42 44 45 46 48 49 50 51 52 53 54 55]




/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


(64, 64)
[[5 0 0]
 [1 3 1]
 [0 1 1]]


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [5]:
print(result2)
print(np.mean(accuracy2))
print(np.std(accuracy2))
print(accuracy2)

[[124.  51.   5.]
 [ 41. 137.  32.]
 [ 21.  41. 108.]]
0.6594120000000001
0.1425599026935695
[0.3636, 0.5455, 0.5455, 0.5455, 0.9167, 0.5455, 0.6364, 0.9091, 0.9091, 0.5, 0.5455, 0.7273, 0.6364, 0.6364, 0.5, 0.3636, 0.6364, 0.8182, 0.9091, 0.5833, 0.5455, 0.8182, 0.7273, 0.7273, 0.6667, 0.7273, 0.7273, 0.5455, 0.7273, 0.5833, 0.6364, 0.8182, 0.3636, 0.6364, 0.5833, 0.8182, 0.5455, 0.7273, 0.7273, 0.6667, 0.8182, 0.4545, 0.9091, 0.6364, 0.5833, 0.8182, 0.6364, 0.5455, 0.7273, 0.75]
